### ISSUE TITLE
Issue about model_config in mmdet

### ISSUE THREAD

**Issue by LuFan31** [djghosh13/geneval#6] opened 2024-07-04 14:27 UTC
Hi, thank you for your great work!

I want to konw which `model_config` file in which version of `mmdet` used [here](https://github.com/djghosh13/geneval/blob/main/evaluation/evaluate_images.py#L39) when evaluating GenEval? Considering `mmdet==2.27.0` needs to be installed, and 'configs/mask2former/mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.py' is specified in code, I download the `configs` folder from [mmdet v2.27.0](https://github.com/open-mmlab/mmdetection/tree/v2.27.0/configs), and set  the `configs/mask2former/mask2former_swin-s-p4-w7-224_lsj_8x2_50e_coco.py` as  args.model_config.

But too many weight download from [download_models.sh](https://github.com/djghosh13/geneval/blob/main/evaluation/download_models.sh) can not match the model initialized based on the args.model_config, and all the final metrics are 0. I think this is because I don't use the correct model_config?

Best,
Fan Lu

**Comment by djghosh13** [comment] 2024-08-13 00:07
Hopefully the problem is fixed by the solution proposed in #8 (the PR is also merged, so pulling the latest commit and re-installing should work as well).

**Closed by djghosh13** 2024-08-13 00:07 UTC
